# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crongrep < Formula
  desc "crongrep is a tool to grep with cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.4/crongrep_1.10.4_darwin_amd64.tar.gz"
      sha256 "d1429c8af59c2503ba488b39171b5e352c41955332306813d5811d99d3279253"

      def install
        bin.install 'crongrep'
      end
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.4/crongrep_1.10.4_darwin_arm64.tar.gz"
      sha256 "16bba0b2373487cdd7d63fa530676382b0299441aa26b9d49ee59a6d542f8388"

      def install
        bin.install 'crongrep'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.4/crongrep_1.10.4_linux_amd64.tar.gz"
        sha256 "047234505b1de8b38dd1d60c5e7cb3d1dd4d9183b7a74d70ed11865c0d507c9e"

        def install
          bin.install 'crongrep'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.4/crongrep_1.10.4_linux_arm64.tar.gz"
        sha256 "fdc83a44726572a2aaed072bd966bbb4faf1ab24f62dbcef0ddb241921ee743e"

        def install
          bin.install 'crongrep'
        end
      end
    end
  end
end
