# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronplan < Formula
  desc "cronplan is a tool to show next triggers for AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.2.1/cronplan_1.2.1_darwin_amd64.tar.gz"
      sha256 "b0061a9f68537d529cd97ab88e1cf6467902be2e5a42f234325d54ae0d49d25c"

      def install
        bin.install 'cronplan'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.2.1/cronplan_1.2.1_darwin_arm64.tar.gz"
      sha256 "0ce42eaaf36df57fabf41e212e6e27396e79c33ef293cf77afa5be23a42b400a"

      def install
        bin.install 'cronplan'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.2.1/cronplan_1.2.1_linux_arm64.tar.gz"
      sha256 "3b2bc3b5c2665ed35d3ee3fcd4525f5f03cac3b2c61345cd897f0c32988effba"

      def install
        bin.install 'cronplan'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.2.1/cronplan_1.2.1_linux_amd64.tar.gz"
      sha256 "e3579dce596fc25589602a51b4df71f10d3cedac1262a4648cdaa7b13dc7622f"

      def install
        bin.install 'cronplan'
      end
    end
  end
end
