# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronparse < Formula
  desc "cronnext is a tool to show next triggers for cron expression."
  homepage "https://github.com/winebarrel/cronparse"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronparse_1.5.0_darwin_arm64.tar.gz"
      sha256 "65ffc3d53a73f9163083be37fe7d563f56f6e49161c92a205300f8456419a30c"

      def install
        bin.install 'cronnext'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronparse_1.5.0_darwin_amd64.tar.gz"
      sha256 "da9510915bfbe34d5e9f54a3e44538b3ac652b07279b48a626048d48f02a61b4"

      def install
        bin.install 'cronnext'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronparse_1.5.0_linux_amd64.tar.gz"
      sha256 "4273456b39a9320d756123f5914013f18952d64874c59958a25a2b8cbce9ee84"

      def install
        bin.install 'cronnext'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronparse_1.5.0_linux_arm64.tar.gz"
      sha256 "a875e63b6fdd8de80a53e07200fd91fd060b96380222b25c194edb8e4da984a8"

      def install
        bin.install 'cronnext'
      end
    end
  end
end
