# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronskd < Formula
  desc "cronskd is a tool to show a schedule of cron expressions."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.0/cronskd_2.0.0_darwin_amd64.tar.gz"
      sha256 "010833b665b65793e8342262f86cc5c4dd84ad92230611a562598efd1524dad9"

      def install
        bin.install 'cronskd'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.0/cronskd_2.0.0_darwin_arm64.tar.gz"
      sha256 "7cde9d60d84381359e73ce683b320762adbd6686d2459b749a4f0fe74006f7f1"

      def install
        bin.install 'cronskd'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.0/cronskd_2.0.0_linux_amd64.tar.gz"
      sha256 "979a0b7297f164775b71bc6b874e8554e3a363dd7e0b76babdb6cbd6667dfb11"
      def install
        bin.install 'cronskd'
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.0/cronskd_2.0.0_linux_arm64.tar.gz"
      sha256 "490b72c5fda17f40ef71b93411da19c2ff66f3e0d31a799ad8d8c44ee64c0f28"
      def install
        bin.install 'cronskd'
      end
    end
  end
end
