# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronmatch < Formula
  desc "cronmatch is a tool to check if datetime matches AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.0/cronmatch_1.10.0_darwin_amd64.tar.gz"
      sha256 "2573dc7cc37d0670439224de457322853b59e47799dda8dfd82df3ac9980ac97"

      def install
        bin.install 'cronmatch'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.0/cronmatch_1.10.0_darwin_arm64.tar.gz"
      sha256 "bf37f372a393e8cea50335679f4fabe5238eb0fb08bd28cef1d595f1479a3d82"

      def install
        bin.install 'cronmatch'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.0/cronmatch_1.10.0_linux_arm64.tar.gz"
      sha256 "e8e543629bcfa269c8cbfab66159fc983461c09ebeb7d39b6fc52770b81f579e"

      def install
        bin.install 'cronmatch'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.0/cronmatch_1.10.0_linux_amd64.tar.gz"
      sha256 "e12bb1c6c711aec1884cc87d86e031f697504375a184b8f918015cc2382a105e"

      def install
        bin.install 'cronmatch'
      end
    end
  end
end
