# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronplan < Formula
  desc "cronplan is a tool to show next triggers for AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.9.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.9.1/cronplan_1.9.1_darwin_arm64.tar.gz"
      sha256 "bcff98371e322be18ef2c0195ffd54c0a17990be68959208d440433845473563"

      def install
        bin.install 'cronplan'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.9.1/cronplan_1.9.1_darwin_amd64.tar.gz"
      sha256 "b7fec86997ea03794f7a70588b9ec7d31942f4d18f72dc72b1948bc8d903837a"

      def install
        bin.install 'cronplan'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.9.1/cronplan_1.9.1_linux_arm64.tar.gz"
      sha256 "9aeac88a8b79b8d14b50430302a7ad00726bc159007930647d358c518a2010f1"

      def install
        bin.install 'cronplan'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.9.1/cronplan_1.9.1_linux_amd64.tar.gz"
      sha256 "f970d1ae5bf1f450bf3f13dcf9234104ccd789b7ae73d088bdd027b7381795e0"

      def install
        bin.install 'cronplan'
      end
    end
  end
end
