# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronnext < Formula
  desc "cronnext is a tool to show next triggers for cron expression."
  homepage "https://github.com/winebarrel/cronparse"
  version "1.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.2/cronnext_1.5.2_darwin_amd64.tar.gz"
      sha256 "7da6aad65842be3583b60fdae4d9d9e94a7bdde6eac871299aa0e85f4a11eabc"

      def install
        bin.install 'cronnext'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.2/cronnext_1.5.2_darwin_arm64.tar.gz"
      sha256 "d72410336c478d0af9dd75df44bedd16dee855351bc1ba55f633f19b6a2d578c"

      def install
        bin.install 'cronnext'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.2/cronnext_1.5.2_linux_arm64.tar.gz"
      sha256 "0b343f77b5fae8356b8447e31d73104e79a2d00ee73a2bd2eff3402c52369363"

      def install
        bin.install 'cronnext'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.2/cronnext_1.5.2_linux_amd64.tar.gz"
      sha256 "c552e3fc3af32fbf615f4711bbb3478b835e3d5b99fc7fed948bda934435a406"

      def install
        bin.install 'cronnext'
      end
    end
  end
end
