# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronviz < Formula
  desc "cronviz is a tool to visualize cron schedule."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronviz_1.10.3_darwin_amd64.tar.gz"
      sha256 "d8779ed27405f365b313bdcc816212482d4a19be1fcff25e446d85ff9693e6cc"

      def install
        bin.install 'cronviz'
      end
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronviz_1.10.3_darwin_arm64.tar.gz"
      sha256 "4bafa8e64c7031c3938a81a0153b5a6ed5647ea95869204efda7b39a56874c19"

      def install
        bin.install 'cronviz'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronviz_1.10.3_linux_amd64.tar.gz"
        sha256 "88e2cc664dd1f45c9e0276e71c228d17d854c53f684542651f088f2ffdcc1e37"

        def install
          bin.install 'cronviz'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronviz_1.10.3_linux_arm64.tar.gz"
        sha256 "1ad0f36576bf596f6272947d715277f43668a444c57ba54e9605ce6c39e4e22c"

        def install
          bin.install 'cronviz'
        end
      end
    end
  end
end
