# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronskd < Formula
  desc "cronskd is a tool to show a schedule of cron expressions."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronskd_1.10.3_darwin_amd64.tar.gz"
      sha256 "66dc47f0e2684d4e9d500b68a1b206cc3ba688d231d966f76df11a52d5905b9f"

      def install
        bin.install 'cronskd'
      end
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronskd_1.10.3_darwin_arm64.tar.gz"
      sha256 "802f4e1da41ea7eb6e876c2b17e1029ce5878657509ad806e656d3400b86767e"

      def install
        bin.install 'cronskd'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronskd_1.10.3_linux_amd64.tar.gz"
        sha256 "e4322cfe9c23e0a7942ff66d27093acf91eb7c709170ca127664c87c896c4985"

        def install
          bin.install 'cronskd'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronskd_1.10.3_linux_arm64.tar.gz"
        sha256 "793aa9c67afe162233d4b72c1036b36d2e97bc42ac180b85d85197ec8d89e71f"

        def install
          bin.install 'cronskd'
        end
      end
    end
  end
end
