# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crongrep < Formula
  desc "crongrep is a tool to grep with cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.1/crongrep_1.10.1_darwin_amd64.tar.gz"
      sha256 "f20e4b8afff93a659fd6297c6c6f2e95fce0a7d7c11e187c0b33f478809a62c0"

      def install
        bin.install 'crongrep'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.1/crongrep_1.10.1_darwin_arm64.tar.gz"
      sha256 "21f96a99ead1024d2e8d052a2ffb4d611eea16a0053c10ed1a70b3a78f3cafbb"

      def install
        bin.install 'crongrep'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.1/crongrep_1.10.1_linux_amd64.tar.gz"
      sha256 "841cf3d13bd52c11280544ff0339acac885ac10c65ecd80d9600958620c453fa"

      def install
        bin.install 'crongrep'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.1/crongrep_1.10.1_linux_arm64.tar.gz"
      sha256 "996f29e2b66ca8d064292beec9b82831f1e6a53ed1b2eb507423c3db7e1afeb2"

      def install
        bin.install 'crongrep'
      end
    end
  end
end
