# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronmatch < Formula
  desc "cronmatch is a tool to check if datetime matches AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronmatch_1.10.3_darwin_amd64.tar.gz"
      sha256 "8861a784d897512bbecbd31106068c7ad18ad1a0ed8d484e2a5791116b1e9405"

      def install
        bin.install 'cronmatch'
      end
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronmatch_1.10.3_darwin_arm64.tar.gz"
      sha256 "5619ab9f4267de2b2d23cfdbaad3c9a90dfeaa08e98710e3010abb7e5d2048ed"

      def install
        bin.install 'cronmatch'
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronmatch_1.10.3_linux_amd64.tar.gz"
        sha256 "789a4e2b33bc703523c5038c948098f28c8a5739d3837d94418e03119c50b638"

        def install
          bin.install 'cronmatch'
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.3/cronmatch_1.10.3_linux_arm64.tar.gz"
        sha256 "5fa049d38d12255f83a37fd6d5e394b6ff250b128f202a5b299eb3be32dabef5"

        def install
          bin.install 'cronmatch'
        end
      end
    end
  end
end
