# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronskd < Formula
  desc "cronskd is a tool to show a schedule of cron expressions."
  homepage "https://github.com/winebarrel/cronplan"
  version "1.10.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.5/cronskd_1.10.5_darwin_amd64.tar.gz"
      sha256 "64ccf93e94f5150e6e76fed96d78ab8541fc83f624e56351a90fc48a9bc8b445"

      def install
        bin.install 'cronskd'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronplan/releases/download/v1.10.5/cronskd_1.10.5_darwin_arm64.tar.gz"
      sha256 "ba3d8db0ae0291dba81970c57011a5663c747b57a76c913e3af656d84d4b282d"

      def install
        bin.install 'cronskd'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.5/cronskd_1.10.5_linux_amd64.tar.gz"
        sha256 "cc11bc80b8bb929edd9d17864475026bf3eb682ae11ce40bf397dc515a0d1b95"

        def install
          bin.install 'cronskd'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/winebarrel/cronplan/releases/download/v1.10.5/cronskd_1.10.5_linux_arm64.tar.gz"
        sha256 "057947e3b051b01ef49ad189ef089bf1c8a8bef4bfc72980e3f6aa86110ff57b"

        def install
          bin.install 'cronskd'
        end
      end
    end
  end
end
