# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronnext < Formula
  desc "cronnext is a tool to show next triggers for cron expression."
  homepage "https://github.com/winebarrel/cronparse"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronnext_1.5.0_darwin_amd64.tar.gz"
      sha256 "4ec5f80e9c4251f0c9ac3656f48e1017581239ae81a3ef5ad0b998706696648b"

      def install
        bin.install 'cronnext'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronnext_1.5.0_darwin_arm64.tar.gz"
      sha256 "a96918093a44d39d71f408341ddf0aef7dd404caea2b3856308ec9a3ce4ca07c"

      def install
        bin.install 'cronnext'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronnext_1.5.0_linux_amd64.tar.gz"
      sha256 "e13f5f04cd84c26cf2c24fe529e8a7bcb9d0674b178243381d44c59fb1801551"

      def install
        bin.install 'cronnext'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/winebarrel/cronparse/releases/download/v1.5.0/cronnext_1.5.0_linux_arm64.tar.gz"
      sha256 "ad3893d1000020951fe1c9e5fcd05f6f040a84d3689202ffa1a8b639dc3c5354"

      def install
        bin.install 'cronnext'
      end
    end
  end
end
