# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronmatch" do
  desc "cronmatch is a tool to check if datetime matches AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronmatch"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronmatch_2.0.2_darwin_amd64.tar.gz"
      sha256 "a25e9f6d717389a3649b4c4dff9d33eea3f5e4c0819f9eb73a4eec6d03b25b2a"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronmatch_2.0.2_darwin_arm64.tar.gz"
      sha256 "9ab2d06771fd8539dd450f3c6970a441fda6cd3cc41c7c05374e43363155e10f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronmatch_2.0.2_linux_amd64.tar.gz"
      sha256 "40382194400e8b326351684a64e1a406f4a42ae9ebc7c983edb6c36d0e77518a"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronmatch_2.0.2_linux_arm64.tar.gz"
      sha256 "c7793f5522365a429c9769eeeb0c32050708703487a0e0ef99a32d773e36f20b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronmatch"]
    end
  end

  # No zap stanza required
end
