# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronmatch" do
  desc "cronmatch is a tool to check if datetime matches AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronmatch"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronmatch_2.0.1_darwin_amd64.tar.gz"
      sha256 "b13a52c76865010d3714cb34584a1cedd7b42d0fa40624385cb88780e868e6d2"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronmatch_2.0.1_darwin_arm64.tar.gz"
      sha256 "49f81eaee05a15bfd9ef09fc0b2e333002e7bf7f83e42187a47f8cc3a26a0cab"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronmatch_2.0.1_linux_amd64.tar.gz"
      sha256 "f565016ebf21967ad211452acf26d4b984504377c2dad1d079f29a9e7fc3dc89"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronmatch_2.0.1_linux_arm64.tar.gz"
      sha256 "141390d8d5b408c713d9793278bd2486d8559a1f7b89e2d44e247bf49326e9c7"
    end
  end

  # No zap stanza required
end
