# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronplan" do
  name "cronplan"
  desc "cronplan is a tool to show next triggers for AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronplan"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronplan_#{version}_darwin_amd64.tar.gz"
      sha256 "d177e7d53ee96c75e7c19248bedd64131ce1524c1b6886f8ae4cac61e098f0a0"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronplan_#{version}_darwin_arm64.tar.gz"
      sha256 "f26f27d970f457a91eccf5e72786b9f692025f8be7837c3854fbfab82edbca10"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronplan_#{version}_linux_amd64.tar.gz"
      sha256 "08b35d3228d5a62d840480dd78a977159908ac472d1ac15ef1f5d2e365a42e5b"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronplan_#{version}_linux_arm64.tar.gz"
      sha256 "c40a2db561a4da4b0d43bc602381f59d97f836dfc2dec14b1c32afde01faaaa3"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronplan"]
    end
  end

  # No zap stanza required
end
