# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronviz" do
  name "cronviz"
  desc "cronviz is a tool to visualize cron schedule."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronviz"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronviz_#{version}_darwin_amd64.tar.gz"
      sha256 "6593c5846ccbf597dc8eb2aec2b3eceee6bf6313ee8fe49d6ea02325c2a06f14"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronviz_#{version}_darwin_arm64.tar.gz"
      sha256 "13f8fa5793ce753f36376ca738ebeb606751e636336f6a58b938b9d87f881949"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronviz_#{version}_linux_amd64.tar.gz"
      sha256 "a2469d78184075082254e636dfac32ef3122d3844491f71d876f963944aaf40c"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronviz_#{version}_linux_arm64.tar.gz"
      sha256 "d4d3de16da5ad7d08025ff86ef43e048007fd1cc1a5c7173c89bb71821084efa"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronviz"]
    end
  end

  # No zap stanza required
end
