# This file was generated by GoReleaser. DO NOT EDIT.
cask "crongrep" do
  desc "crongrep is a tool to grep with cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crongrep"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/crongrep_2.0.1_darwin_amd64.tar.gz"
      sha256 "ceace7b1857040bdc4db100baf718cd6a095c00184196415081fc1279d52bb18"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/crongrep_2.0.1_darwin_arm64.tar.gz"
      sha256 "f66418004041dd5aede348b9708b08e29d23b46e7e4fe371c74759d9b2e04415"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/crongrep_2.0.1_linux_amd64.tar.gz"
      sha256 "0737d4ed55c3fe08a3d56e510f8408946a48ae82825fb904012ef44332818940"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/crongrep_2.0.1_linux_arm64.tar.gz"
      sha256 "0f592e5ebebcd6f808763456103983b3da4f3f6244adfe18fce88bd36b56b1cc"
    end
  end

  # No zap stanza required
end
