# This file was generated by GoReleaser. DO NOT EDIT.
cask "crongrep" do
  name "crongrep"
  desc "crongrep is a tool to grep with cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crongrep"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/crongrep_#{version}_darwin_amd64.tar.gz"
      sha256 "0989e8ede48ce4a6658ebdbd8bc28c85c66e81f41cb001fae9a3173f1525639e"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/crongrep_#{version}_darwin_arm64.tar.gz"
      sha256 "223cb0f397fa17d2cefd2e2ec2944638e97b01c4d36e2109caa727df2a043475"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/crongrep_#{version}_linux_amd64.tar.gz"
      sha256 "3713c85342a565ee155824bdb1cf38f79646829f550b457686c90ade31e477ba"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/crongrep_#{version}_linux_arm64.tar.gz"
      sha256 "55d62c7766b7a0c1fc547a8fb03679e9835027fe10593e05fff34ddda95f9308"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crongrep"]
    end
  end

  # No zap stanza required
end
