# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronplan" do
  desc "cronplan is a tool to show next triggers for AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronplan"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronplan_2.0.1_darwin_amd64.tar.gz"
      sha256 "23e200e1c222c2a7627f21673d435052a4777d803de5a121e82cf0debbfcfd44"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronplan_2.0.1_darwin_arm64.tar.gz"
      sha256 "112db4d266779085f38b10d73ebf7aa0771655a85cdcad6241a08b018a8cff0d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronplan_2.0.1_linux_amd64.tar.gz"
      sha256 "4065b3eb897b8b22b948fba8894a1f580c2ae83423813253fe5b8fce86ade30b"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronplan_2.0.1_linux_arm64.tar.gz"
      sha256 "b56d769f3f1fb8d03b14e51180b841c15372b55960ff5de690f74d74f59ec41d"
    end
  end

  # No zap stanza required
end
