# This file was generated by GoReleaser. DO NOT EDIT.
cask "crongrep" do
  desc "crongrep is a tool to grep with cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crongrep"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/crongrep_2.0.2_darwin_amd64.tar.gz"
      sha256 "2ae377b1d0e67ea4db426f9edb5fbce778512132a003b7d587a9072ca085f510"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/crongrep_2.0.2_darwin_arm64.tar.gz"
      sha256 "227a6d69623a3fc3a1a05b1d18af0a8d88f762b6476c1afef47f078313a4c573"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/crongrep_2.0.2_linux_amd64.tar.gz"
      sha256 "3177949f4436943d3593e60b375e34b79f97d54d21a5cd096d8650c240bb942c"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/crongrep_2.0.2_linux_arm64.tar.gz"
      sha256 "3466c3f06a2b9076037139aa2c42186e9624d7b85af2a82f68c74bcb2aaea401"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/crongrep"]
    end
  end

  # No zap stanza required
end
