# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronviz" do
  desc "cronviz is a tool to visualize cron schedule."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronviz"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronviz_2.0.1_darwin_amd64.tar.gz"
      sha256 "f6a517c06a2c0623b16dcae98c017a568c7f9dc6f5894a18348e15bcb5cf59f4"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronviz_2.0.1_darwin_arm64.tar.gz"
      sha256 "524f4bc08dc498f9d07a9bed80f7e471022f01df4d8d89578f99f379ef77e8c5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronviz_2.0.1_linux_amd64.tar.gz"
      sha256 "f69fb7253175ee6b64aeef5f271310f3f00505badc7d7f2f0027335cc0d8cc1a"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronviz_2.0.1_linux_arm64.tar.gz"
      sha256 "9d1a471a0d38094ca19fc01d7f8b93098c079612d4ba112390677666db296c09"
    end
  end

  # No zap stanza required
end
