# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronmatch" do
  name "cronmatch"
  desc "cronmatch is a tool to check if datetime matches AWS cron expression."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronmatch"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronmatch_#{version}_darwin_amd64.tar.gz"
      sha256 "b6cadc93263924f51c3dbb6fe75d4affc4f818273656907a9d66d49f63f0e069"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronmatch_#{version}_darwin_arm64.tar.gz"
      sha256 "06e6dba3bd24c2fb6b65ff546db17e5045866ce0c7f815eb3ca8e50a443a9a76"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronmatch_#{version}_linux_amd64.tar.gz"
      sha256 "dbc134fa32de922d1efc57fffaec948d0695844101e39fe64b177dc04edfebb6"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronmatch_#{version}_linux_arm64.tar.gz"
      sha256 "2a83457fc0f0eeaa570f602332229b5077e124cd9a102f38407865d1eb434902"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronmatch"]
    end
  end

  # No zap stanza required
end
