# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronskd" do
  desc "cronskd is a tool to show a schedule of cron expressions."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronskd"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronskd_2.0.1_darwin_amd64.tar.gz"
      sha256 "095a75ef060f3ba31535b6cdd323e1f97d6a705da5f84de12c83192f59144cda"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronskd_2.0.1_darwin_arm64.tar.gz"
      sha256 "3a72ac29e2ed01abef5fde2f95610499e593e293e914a98a35f561e0d2336bf6"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronskd_2.0.1_linux_amd64.tar.gz"
      sha256 "28b6e1b22bc333bfd6f629eec9bcb1a194c27ceb40484655a2cb825ad62180a2"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.1/cronskd_2.0.1_linux_arm64.tar.gz"
      sha256 "ef3150accfcc8ac07293b255f123e0ab5edaf93441f761ca7ce97c2c15892cc1"
    end
  end

  # No zap stanza required
end
