# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronskd" do
  name "cronskd"
  desc "cronskd is a tool to show a schedule of cron expressions."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronskd"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronskd_#{version}_darwin_amd64.tar.gz"
      sha256 "81dee7a393a9a87220c51beb5e8e0d0404587f1bfb7148e1235918727afc794f"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronskd_#{version}_darwin_arm64.tar.gz"
      sha256 "7ebe83d9a644a8c6cc5b32718f4fb7351e16e1f4e580706a0c30298e97e9d20c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronskd_#{version}_linux_amd64.tar.gz"
      sha256 "94e8980e7e80b95ea653849f8051ba8e1d04287e24b7d63b9efa1364104cedc1"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v#{version}/cronskd_#{version}_linux_arm64.tar.gz"
      sha256 "0bce198fba198b0b03fbed7658e446f4705657724a61f5b10613a26d35c59a92"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronskd"]
    end
  end

  # No zap stanza required
end
