# This file was generated by GoReleaser. DO NOT EDIT.
cask "cronskd" do
  desc "cronskd is a tool to show a schedule of cron expressions."
  homepage "https://github.com/winebarrel/cronplan"
  version "2.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cronskd"

  on_macos do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronskd_2.0.2_darwin_amd64.tar.gz"
      sha256 "4b3fc3600a0c7d8f2e51b5d32285c92d370a9df2a9b5028cc0791271a63057b1"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronskd_2.0.2_darwin_arm64.tar.gz"
      sha256 "469a793023381fc6e9f4fe975a046ffc631fc7d8212ca923fa9cb0bebdb61fe2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronskd_2.0.2_linux_amd64.tar.gz"
      sha256 "94a120283ddcc50c8dfa2386218d4927cfdeefb8c5be0459f4f40ccac67e5308"
    end
    on_arm do
      url "https://github.com/winebarrel/cronplan/releases/download/v2.0.2/cronskd_2.0.2_linux_arm64.tar.gz"
      sha256 "39ea9304b0e5fa934218b5f68feb312bb0124ca1509fd60c8c9c7466e9297466"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cronskd"]
    end
  end

  # No zap stanza required
end
